export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_ALL_SERIES = 'GET_ALL_SERIES';
export const GET_TOP_MOVIES = 'GET_TOP_MOVIES'; 
export const GET_MOVIE_BY_TITLE = 'GET_MOVIE_BY_TITLE'
export const GET_ALL_MOVIES_FILTERED = 'GET_ALL_MOVIES_FILTERED';
export const GET_ALL_SERIES_FILTERED = 'GET_ALL_SERIES_FILTERED';
export const GET_SERIE_BY_TITLE = 'GET_SERIE_BY_TITLE'
export const GET_TOP_SERIES = 'GET_TOP_SERIES'; 
